---
title: "MB_2016ResearchDay"
author: "MB, HQ"
date: "March 24, 2016"
output: html_document
---

Useful references:
CV https://www.youtube.com/watch?v=lAE3Xll9yoE

Qin tutorial:  https://www.youtube.com/watch?v=gC-WuK4BbJY

DNA microarray: https://www.youtube.com/watch?v=VNsThMNjKhM

The R markdown file for MB 2016 Resaerc Day. 

```{r}
rm(list=ls())
require(GEOquery)

#http://www.ncbi.nlm.nih.gov/geo/browse/
#GEO2R 

myfiles = read.table("geo_GPL2529.tab", head=F, sep="\t")
myGSEs = as.character( myfiles[,1] )
myGSEs 
```

GSE37466
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE37466

GSE27085
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE27085

GSE30053
http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE30053

```{r}
myGSE = "GSE37466"
myGSE= "GSE27085"
myGSE= "GSE30053"

  outfilename = paste( "output/", myGSE, "_log2CV.csv", sep='')
  
gset <- getGEO(myGSE, GSEMatrix =TRUE)
if (length(gset) > 1) idx <- grep("GPL90", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

ex <- exprs(gset) #This is the expression matrix
```

Now, preprocessing
```{r}
dictionary = gset@featureData@data[, c('ID', 'ORF')]  #This is a lookup table for probe ID and ORF 

ORFs = unique(as.character(dictionary$ORF))
yORFs = ORFs[grep( "Y\\w{2}\\d{3}.*", ORFs)]  #these are yeast ORFs
str(yORFs)
setdiff(ORFs, yORFs)

#yORFFlag = 'good'
#if (length(yORFs) < 1000) { yoORFFlag = 'toofewORFs' }

ORFs = yORFs

#########
# A simple approach to create an expression matrix with ORFs as row names
# This approach takes only one probe for each ORFs, which is often true for cDNA arrays

ex2 = ex[match(ORFs, dictionary$ORF), ]   
rownames(ex2) = ORFs
head(ex2) #Now, expression matrix is named by ORFs

##########
#Another approach is to calculate the average sigals for all the probes in the same ORFs
multipleORFs = NA;
ex3 = ex2 #This is just a template
# orf = 'YLR331C'
for (orf in ORFs) {
  myrows = as.character( dictionary$ID[dictionary$ORF==orf] )
  if (length(myrows) > 1) {
    print (orf)
    multipleORFs = c(multipleORFs, orf)
    ex[myrows, ] = apply(ex[myrows,], 2, mean) 
  }else {
    ex3[orf, ] = ex[myrows[1], ]
  }
}
#multipleORFs = multipleORFs[-1]

######
#normalizaion  
colSums = apply(ex3, 2, sum)
colSums/1E6
ex3norm = ex3
for( col in 1:length(ex3[1,])) {
  ex3norm[,col] = ex3[,col] * max(colSums) / sum(ex3[,col])
}
apply(ex3norm, 2, sum) / max(colSums)
ex3 = ex3norm 
```

now, have a look at the signals
```{r}
hist(ex3[,1], br=100)
ex4 = log2(ex3)
hist(ex4[,3])
ex4[ex4<0] = NA #remove backgrounds
myVar = apply( ex4, 1, FUN=function(x){var(x, na.rm=T)})
myStddev = sqrt(myVar)
myMean = apply( ex4, 1, FUN=function(x){mean(x, na.rm=T)})
myCV = myStddev / myMean
myarray= data.frame(cbind( myStddev, myMean, myCV))
myarray$ORF = ORFs
myarray = myarray[, c(4, 1:3)]
summary(myarray)
hist(myarray$myCV, main=myGSE, xlab="CV", br=60)
```

